version: "3.0"
services:

  web:
    image: "naps62/mse:${MSE_VERSION}"
    command: foreground
    depends_on:
      - db
    ports:
      - "4000:4000"
    environment:
      DATABASE_URL: "ecto://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db/${POSTGRES_DB}"
      PROXY_PORT: 4001
      WEB_PORT: 4000
      ADMIN_PORT: 4002
      POOL_SIZE: 10
      ADMIN_USERNAME: "${ADMIN_USERNAME}"
      ADMIN_PASSWORD: "${ADMIN_PASSWORD}"

  db:
    image: postgres:9.6.2
    environment:
      POSTGRES_DB: "${POSTGRES_DB}"
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
    volumes:
      - db-volume:/var/lib/postgresql/data

  pgbackups:
    image: schickling/postgres-backup-s3
    volumes:
      - /root/mse-production/backups:/mnt/backups
    depends_on:
      - db
    environment:
      SCHEDULE: "@daily"
      S3_REGION: "${S3_REGION}"
      S3_ACCESS_KEY_ID: "${S3_ACCESS_KEY_ID}"
      S3_SECRET_ACCESS_KEY: "${S3_SECRET_ACCESS_KEY}"
      S3_BUCKET: "${S3_BUCKET}"
      S3_PREFIX: "db-backups"
      POSTGRES_DATABASE: "${POSTGRES_DB}"
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"

volumes:
  db-volume:
