version: "2.0"
services:

  web:
    image: "naps62/mse:${MSE_VERSION}"
    command: foreground
    depends_on:
      - db
      - redis
    ports:
      - "4000:4000"
    environment:
      DATABASE_URL: "ecto://mse_prod:mse_prod@db/mse_prod"
      PORT: 4000
      POOL_SIZE: 10
      ADMIN_USERNAME: naps62
      ADMIN_PASSWORD: naps62

  db:
    image: postgres:9.6.2
    environment:
      POSTGRES_DB: "mse_prod"
      POSTGRES_USER: "mse_prod"
      POSTGRES_PASSWORD: "mse_prod"

  redis:
    image: "redis:3.0"
