version: "3.0"
services:

  web:
    image: "naps62/mtgsearch:${MTGSEARCH_VERSION}"
    command: foreground
    depends_on:
      - db
    expose:
      - "80"
    environment:
      VIRTUAL_HOST: "mtgsear.ch,admin.mtgsear.ch"
      MIX_ENV: prod
      DATABASE_URL: "ecto://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db/${POSTGRES_DB}"
      PROXY_PORT: 80
      WEB_PORT: 4001
      ADMIN_PORT: 4002
      POOL_SIZE: 10
      ADMIN_USERNAME: "${ADMIN_USERNAME}"
      ADMIN_PASSWORD: "${ADMIN_PASSWORD}"

  db:
    image: postgres:9.6.2
    environment:
      POSTGRES_DB: "${POSTGRES_DB}"
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
    volumes:
      - db-volume:/var/lib/postgresql/data

  pgbackups:
    image: schickling/postgres-backup-s3
    volumes:
      - /tmp:/mnt/backups
    depends_on:
      - db
    environment:
      SCHEDULE: "@daily"
      S3_REGION: "${S3_REGION}"
      S3_ACCESS_KEY_ID: "${S3_ACCESS_KEY_ID}"
      S3_SECRET_ACCESS_KEY: "${S3_SECRET_ACCESS_KEY}"
      S3_BUCKET: "${S3_BUCKET}"
      S3_PREFIX: "db/prod"
      POSTGRES_HOST: "db"
      POSTGRES_DATABASE: "${POSTGRES_DB}"
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"

volumes:
  db-volume:

networks:
  default:
    external:
      name: nginx-proxy
